{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-04-14T12:12:10Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      fix: upgrade to version 0.1.21

      from: https://github.com/jenkins-x-plugins/jx-secret.git
    sha: 6bff527d8ce7e50c3d1d57da5d0afd42ea70dc19
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      fix: upgrade to version 0.1.20

      from: https://github.com/jenkins-x-plugins/jx-secret.git
    sha: 82c038b87b23f1152b425530bdaa23fe9d925e7c
  gitHttpUrl: https://github.com/jenkins-x/jx
  gitOwner: jenkins-x
  gitRepository: jx
  name: '{{ .Chart.Name }}'
  version: 3.2.34
status: {}
 
{{- end }}
