{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-05-17T14:06:10Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot-test
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot-test
    message: |
      fix: upgrade to version 0.0.183

      from: https://github.com/jenkins-x-plugins/jx-admin
    sha: 4b0bce00e5473e61873e426585618f598293ff07
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore(deps): upgrade jenkins-x/jx to version 0.1.14

      from: https://github.com/jenkins-x-plugins/jx-project.git
    sha: 446f9486e850eb75e5f4b98ad9553d13a017ac76
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot-test
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot-test
    message: |
      fix: upgrade to version 0.0.265

      from: https://github.com/jenkins-x-plugins/jx-promote
    sha: 476ec5bccf5685bc6af40c5077d1625582fc96c9
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore(deps): upgrade jenkins-x/jx to version 0.0.76

      from: https://github.com/jenkins-x-plugins/jx-verify.git
    sha: 8545666170fcc11a2c742bf3fcceea2f3d35078e
  - author:
      email: jenkins-x@googlegroups.com
      name: root
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: root
    message: |
      chore(deps): upgrade jenkins-x/jx to version 0.2.87

      from: https://github.com/jenkins-x-plugins/jx-gitops.git
    sha: 4c81c7e96924fbe36ec8ebe297206ba512709acf
  gitHttpUrl: https://github.com/jenkins-x/jx
  gitOwner: jenkins-x
  gitRepository: jx
  name: '{{ .Chart.Name }}'
  version: 3.2.99
status: {}
 
{{- end }}
