{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-06-24T16:16:20Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot-test
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot-test
    message: |
      fix: upgrade to version 0.0.270

      from: https://github.com/jenkins-x-plugins/jx-promote
    sha: bb1408b476d69a78096b2f939d16208b05aa0ea3
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore(deps): upgrade jenkins-x/jx to version 0.2.5

      from: https://github.com/jenkins-x-plugins/jx-project.git
    sha: 27c65f1ede474768bdbea8b549189fe467548449
  gitHttpUrl: https://github.com/jenkins-x/jx
  gitOwner: jenkins-x
  gitRepository: jx
  name: '{{ .Chart.Name }}'
  version: 3.2.150
status: {}
 
{{- end }}
