{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-04-26T15:56:57Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: root
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: root
    message: |
      chore(deps): upgrade jenkins-x/jx to version 0.2.70

      from: https://github.com/jenkins-x-plugins/jx-gitops.git
    sha: 5813a20d4c8d10cf809fd0f83c45b9f73c848657
  - author:
      email: jenkins-x@googlegroups.com
      name: root
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: root
    message: |
      chore(deps): upgrade jenkins-x/jx to version 0.2.69

      from: https://github.com/jenkins-x-plugins/jx-gitops.git
    sha: e72662b072fe480032f5882094765ebf30ffc11d
  gitHttpUrl: https://github.com/jenkins-x/jx
  gitOwner: jenkins-x
  gitRepository: jx
  name: '{{ .Chart.Name }}'
  version: 3.2.63
status: {}
 
{{- end }}
