{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-05-11T15:18:55Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      fix: upgrade to version 0.1.27

      from: https://github.com/jenkins-x-plugins/jx-secret.git
    sha: c4a6b0558e8c944d8cb9b7b646cbd47d694005b2
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      fix: upgrade to version 0.1.26

      from: https://github.com/jenkins-x-plugins/jx-secret.git
    sha: c1f4e1f9e93f8b77fa31dd96f3939aebe31f55b2
  gitHttpUrl: https://github.com/jenkins-x/jx
  gitOwner: jenkins-x
  gitRepository: jx
  name: '{{ .Chart.Name }}'
  version: 3.2.91
status: {}
 
{{- end }}
