{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-05-18T13:51:47Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      fix: upgrade octant
    sha: a382e316786aa8d70282a896d9821b3df2799220
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore(deps): upgrade jenkins-x/jx to version 0.0.136

      from: https://github.com/jenkins-x-plugins/jx-pipeline.git
    sha: ae0891ce4194f9bed82e4e1a8b60959e21d030a3
  gitHttpUrl: https://github.com/jenkins-x/jx
  gitOwner: jenkins-x
  gitRepository: jx
  name: '{{ .Chart.Name }}'
  version: 3.2.103
status: {}
 
{{- end }}
