{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-04-01T12:43:38Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: rawlingsj80@gmail.com
      name: James Rawlings
    branch: master
    committer:
      email: rawlingsj80@gmail.com
      name: James Rawlings
    message: |
      chore: prepare for v3 GA
    sha: dddae5c21a46753a04fd4b9818a8a6cb6b8f14c1
  gitHttpUrl: https://github.com/jenkins-x/jx
  gitOwner: jenkins-x
  gitRepository: jx
  name: '{{ .Chart.Name }}'
  version: 3.2.2
status: {}
 
{{- end }}
