jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: build-make-test
      uses: docker://golang:1.15
      with:
        args: -c "make test linux"
        entrypoint: /bin/sh
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
"on":
  push:
    branches-ignore:
    - main
    - master
